version: '3'
services:
  client:
    image: 'jaimetuyuc7/client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'jaimetuyuc7/server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: 'jaimetuyuc7/worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'jaimetuyuc7/nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'

# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/25113234#questions