version: '3'

services:
  postgress:
    image: postgres:latest
    container_name: postgress
    env_file:
      - postgress.env

  redis:
    image: redis:latest
    container_name: redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    env_file:
      - worker.env
      
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - server.env
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file:
      - client.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
      - postgress
      - redis