apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: jaimetuyuc-com-tls
spec:
  secretName: jaimetuyuc-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jaimetuyuc.com
  dnsNames:
  - jaimetuyuc.com
  - www.jaimetuyuc.com
