apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: jaimetuyuc7/server
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-cluster-ip-service
        - name: REDIS_PORT
          value: "6379"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_HOST
          value: postgres-cluster-ip-service
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "128Mi" # Minimum memory required
            cpu: "250m" # Minimum CPU required
          limits:
            memory: "256Mi" # Maximum memory allowed
            cpu: "500m" # Maximum CPU allowed

# REDIS_HOST=redis REDIS_PORT=6379 PG_USER=postgres PG_HOST=postgress PG_DATABASE=postgres PG_PASSWORD=postgres PG_PORT=5432
